### ISSUE TITLE
Fix included last post:  Multiprocessing and predict don't play nice currently.

### ISSUE THREAD

**Issue by joshring** [lucaskolstad/rBCM#4]
This is the code to generate the error and the error itself:
https://pastebin.com/0rGsDTPY

**So I have a question:**

- Is prediction single threaded currently and is it therefore a bottleneck?
- My natural intuition would be that the training of the GPR would be the largest bottleneck, training is multi-threaded internally already however.

I will take a look at the cause of this, I suspect it could be to do with the bottom of `rBCM.py`:

`# These simply unpack arguments for the fitting and prediction worker function.`
`_worker_fit_wrapper = lambda args: _worker_fit(*args)`
`_worker_predict_wrapper = lambda args: _worker_predict(*args)`

**Comment by joshring** [comment]
I managed to fix the above error, which is related to Lambdas and multiprocessing (which uses pickle internally)
https://stackoverflow.com/questions/4827432/how-to-let-pool-map-take-a-lambda-function

**The fixed code in rBCM.py is here:**
https://pastebin.com/QRxgptb7

**Comment by lucaskolstad** [comment]
Hey I really appreciate the help, but are you familiar with the pull request feature here on github? It makes it a lot easier for me to see exactly which lines differ to understand the changes and merge them in with a single click without looking through as much code and possibly missing some changes as I apply them myself. I can give more direction if needed, and disregard this if you are already familiar, but here are some basic instructions:

1) fork the project so you have your own copy
2) make sure your repo is up-to-date with this upstream repo by adding it as a remote and pulling any changes and addressing any conflicts (this may be needed since I added in the changes you made here just now so your forked version is a commit behind, though if you change different lines it shouldn't conflict)
    ```
    git remote add upstream https://github.com/lucaskolstad/rBCM
    git pull upstream master
    ```
3) make your changes and commit them to your own forked github repo. If you include text referencing issue #4 in the commit message or in the comment section of the pull request it'll auto associate to this issue.
    ```
   git remote add origin https://github.com/joshring/rBCM
   git commit -m "some commit message - issue #4"
   git push origin master
    ```

4) on the page for your repo click the "request pull request" button that will appear after the commit is pushed

You submitted issue #5 with a fix for the example code in the docs, that code can be found in the file `docs/introduction.rst` and would be a good candidate to try this procedure.

But I did make the changes you proposed in this issue just now. thanks for the find! that's a tricky one that lambdas can't be pickled, I wouldn't have guessed that.

**Comment by joshring** [comment]
Thanks,

The issue 5 was a case where things broke, so would not be looking to update the docs with that just yet?
Instead I did some minor refactoring and submitted that as a test case.

Thanks for the information, I was never so hot at git.
